### ISSUE TITLE
Add a feature to use an estimated_document_count when searching or counting with a query

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-Store-MongoDB#17]
This Catmandu package uses the `count_document` method on Mongo collections to calculate the collection size. This is a very fast operation when no query is provided but a very slow operation on very big MongoDB collections with a query.

Provide an optimization flag e.g. `estimate_count => 1` that results in using `estimated_document_count` when a query is provided and `count_document` when no query is provided.

**Comment by nics** [comment]
estimated_document_count doesn't take a filter argument, it can only give a guesstimate of the whole collection

**Comment by phochste** [comment]
@nics My mistake..I meant the other way around

**Comment by nics** [comment]
added estimate_count option to store in 0.0804, can you help test it's effect?
